"""
Django settings for it2202courseapis project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

from django.conf.global_settings import AUTH_USER_MODEL

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_ROOT = '%s/courses/static/' % BASE_DIR

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c=ok!*bb4oi#235a82f$fk8iq!6!f6qss)x&)3ede0h02nv7c$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'courses.apps.CoursesConfig',
    'ckeditor',
    'ckeditor_uploader',
    'rest_framework',
    'drf_yasg',
    'oauth2_provider',

]
# Trả về json thay vì form
OAUTH2_PROVIDER = { 'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.JSONOAuthLibCore' }

REST_FRAMEWORK = {
        'DEFAULT_AUTHENTICATION_CLASSES': (
            'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    )
}

import cloudinary
import cloudinary.uploader
from cloudinary.utils import cloudinary_url

# Configuration
cloudinary.config(
    cloud_name = "ds05mb5xf",
    api_key = "129254722258642",
    api_secret = "OQScAUMjqFmA3g6gog1GfBRCM14", # Click 'View API Keys' above to copy your API secret
    secure=True
)

CKEDITOR_UPLOAD_PATH = "ckeditor/lessons/"


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'it2202courseapis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'it2202courseapis.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'coursedb',
        'USER': 'root',
        'PASSWORD': 'ThanhNam*1909',
        # 'PASSWORD': 'root',
        'HOST': ''  # mặc định localhost
    }
}

AUTH_USER_MODEL= "courses.User"

import pymysql
pymysql.install_as_MySQLdb()

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# CLIENT_ID="maxFpFyIvknFpCsrIBLQj8jl9wlUZXiSRu3lmwbS"
# CLIENT_SECRET="riJrlTJZ9ScyIrO4vVLruBrA8Rp4hGt54D9YGsjeHRGb8l3sd1zjCqnLDDy85KbFn0njwUKDFKufwNkh8ghloBCeg2EKwupVdBQtTj3DPGwf3CXmuBX4fp74In12j5E6"

CLIENT_ID="7I9P1esUERPnkyGE2JTlwk03WBEXGOPSKYtFKbUK"
CLIENT_SECRET="u42Wwafiyz2yOpgZkhA96bbZ3dfXAQSms2PQnc4kuGsfNwuqnbtX2bAO2mcUvWszOyqvWSMD9e3h0lE3DcmL8BGFb2jwo4rj2zdwmDmQgbTu64ZW0UNTH7ZQLfTBCd97"
# POST http://127.0.0.1:8000/o/token/
# {
#     "username": "admin",
#     "password":"123",
#     "client_id":"maxFpFyIvknFpCsrIBLQj8jl9wlUZXiSRu3lmwbS",
#     "client_secret":"riJrlTJZ9ScyIrO4vVLruBrA8Rp4hGt54D9YGsjeHRGb8l3sd1zjCqnLDDy85KbFn0njwUKDFKufwNkh8ghloBCeg2EKwupVdBQtTj3DPGwf3CXmuBX4fp74In12j5E6",
#     "grant_type":"password"

# }
# Lấy user token